package com.narrateddeck.android.domain

import java.io.BufferedOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Builds a zip containing:
 * - scripts.txt (slide index + notes)
 * - slide_NNN.wav (or .ogg/.mp3 if present) per slide that has audio
 *
 * System TTS typically writes WAV; we keep the extension of the source file.
 */
object AudioExporter {

    data class ExportResult(
        val zipFile: File,
        val slideCount: Int,
        val audioCount: Int,
    )

    fun export(
        slides: List<SlideNote>,
        outputDir: File,
        zipFileName: String = "narrateddeck-export.zip",
    ): ExportResult {
        outputDir.mkdirs()
        val zipFile = File(outputDir, zipFileName)
        if (zipFile.exists()) zipFile.delete()

        var audioCount = 0
        ZipOutputStream(BufferedOutputStream(FileOutputStream(zipFile))).use { zos ->
            // scripts.txt
            val scripts = buildString {
                appendLine("# NarratedDeck scripts")
                appendLine("# Generated by NarratedDeck Android MVP")
                appendLine()
                slides.forEach { slide ->
                    appendLine("--- Slide ${slide.index + 1}: ${slide.displayTitle} ---")
                    appendLine(slide.notes.ifBlank { "(no notes)" })
                    appendLine()
                }
            }
            zos.putNextEntry(ZipEntry("scripts.txt"))
            zos.write(scripts.toByteArray(Charsets.UTF_8))
            zos.closeEntry()

            slides.forEach { slide ->
                val path = slide.audioFilePath ?: return@forEach
                val audio = File(path)
                if (!audio.exists() || !audio.isFile) return@forEach
                val ext = audio.extension.ifBlank { "wav" }
                val entryName = "slide_%03d.%s".format(slide.index + 1, ext)
                zos.putNextEntry(ZipEntry(entryName))
                FileInputStream(audio).use { it.copyTo(zos) }
                zos.closeEntry()
                audioCount++
            }
        }

        return ExportResult(
            zipFile = zipFile,
            slideCount = slides.size,
            audioCount = audioCount,
        )
    }
}
